import './globals.css';
import { Inter } from 'next/font/google';
import { TopProgressBar } from './_components/common/Functions';
import Header from './_components/layout/Header';
import Footer from './_components/layout/Footer';
import NextAuthSessionProvider from './providers/sessionProvider';
import { getServerSession } from 'next-auth';
import { authOptions } from './utils/authOptions';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Nextjs Boilerplate',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider session={session}>
          <TopProgressBar />
          <Header />
            {children}
          <Footer />
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
