"use client"
import './globals.css';
import { Inter } from 'next/font/google';
import NextNProgress from 'nextjs-progressbar';
import Header from './_components/layout/Header';
import Footer from './_components/layout/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Nextjs Boilerplate',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextNProgress />
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  )
}
